# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
#'
NULL

vb_cmgfmcpp <- function(XList, typeID, numvarmat, Alist, Z, Mulist_y_int, Slist_y_int, Sigmamlist_int, invLambdalist_int, Blist_int, mulist_int, betalist_int, M_int, S_int, Xi_int, O_int, epsELBO, maxIter, verbose, add_IC_inter = TRUE, update_sigma = TRUE) {
    .Call(`_CMGFM_vb_cmgfmcpp`, XList, typeID, numvarmat, Alist, Z, Mulist_y_int, Slist_y_int, Sigmamlist_int, invLambdalist_int, Blist_int, mulist_int, betalist_int, M_int, S_int, Xi_int, O_int, epsELBO, maxIter, verbose, add_IC_inter, update_sigma)
}

